config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users #symbol notation
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  #from paperclip documentation
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save 
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      
      ContactMailer.contact_email(name, email, body).deliver
      
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = "Message failed to send."
      redirect_to new_contact_path
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)  
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user! #before any action below happens, you must be authenticated and signed up to access pages
  before_action :only_current_user #created method to only allow current user to edit his/her own profile
  
  def new
    # form where a user can fill out their own profile
    @user = User.find(params[:user_id]) #reach into the database and find the user that's loged in
    @profile = Profile.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params) #saves info
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path(params[:user_id])
    else
      render action: :new
    end
  end
  
  def edit
    @user = User.find(params[:user_id])  
    @profile = @user.profile
  end
  
  def update
    @user = User.find(params[:user_id])    
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile Updated!"
      redirect_to user_path(params[:user_id])
    else
      render action: :edit  
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    
    def only_current_user
      @user = User.find(params[:user_id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
####app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :select_plan, only: :new
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! #stops users who aren't signed in from viewing profiles
  
  def index
    @users = User.all #grabs all registered users
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class='row'>
  <%= form_for @contact do |f| %>
  
    <div class="col-md-4 col-md-offset-4">
      <div class='well'>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: "form-control" %>
        </div>
        
        <%= f.submit 'Submit', class: "btn btn-default" %>
      </div>
    </div>
    
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>devMatch</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "http://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => 'stripe-key', :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--<nav class="navbar navbar-default navbar-static-top" role="nagivation">
  <div class="container">
    <div class="navbar-header">
 -->

<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-users"></i>
        devMatch
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, class: 'btn btn-primary navbar-btn', method: :delete %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if %>
          <li><%= link_to "Community", users_path %></li>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
    <h1>Welcome to Dev Match</h1>
    <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>

<div class="row">
    <% if user_signed_in? %>
        <div class="col-md-6">
            <div class="well">  
            <h2 class="text-center">Your Profile</h2>
                <% if current_user.profile %>
                    <%= link_to "Edit your profile!", edit_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block' %><br/>
                    <%= link_to "View your profile!", user_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
                <% else %>
                    <p>Create your profile so that you can share your information with the community.</p>
                    <%= link_to "Create your profile!", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
                <% end %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">The Community</h2>
                <p>Visit the community to meet other developers, entrepreneurs and investors!</p>
                <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
            </div>
        </div>
    <% else %>
        <div class="col-md-6">
            <div class="well">
                <h2 class='text-center'>Basic Membership</h2>
                <h4>Sign up for free and get basic access to the community.</h4>
                <br/>
                <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="well">
                <h2 class='text-center'>Pro Membership</h2>
                <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
                <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
            </div> 
        </div>
    <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Your Profile</h1>
    <p class="text-center">Be a part of the Dev Match community and fill out your profile</p>
    
    <div class='well'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the Dev Match community and fill out your profile</p>
    
    <div class='well'>
      <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :job_title %>
          <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    
    
    
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <ul class="list-unstyled"> <!--removes bulletpoints -->
      <% @users.each do |user| %>
        <% if user.profile %>
          <li>
            <div class="well row <%= cycle('', 'white-bg') %>">
              <div class="col-sm-4 test-center">
                <%= link_to user do %>
                  <%= image_tag user.profile.avatar.url(:thumb), class: "avatar-img" %>
                <% end %>
              </div>
              <div>
                <%= link_to user do %>
                  <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                <% end %>
                <p><%= user.profile.job_title %></p> 
                <% if user.plan_id == 2 %>
                  <span class="label label-danger">Pro</span>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url, class: "avatar-img" %>
  </div>
  <div class="col-md-6">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3><span class="job-title-icon"><%= job_title_icon %></span> <%= @user.profile.job_title %></h3>
    <div class='well profile-description'>
      <h3>Description</h3>
      <%= @user.profile.description %><br/>
    </div>
    
    <div class="well contact-info">
      <% if current_user.plan_id == 2 %>
        <h3>Contact Info</h3>
        <%= @user.profile.phone_number %><br/>
        <%= @user.profile.contact_email %><br/>
      <% else %>
        Sign up for Pro membership to view contact info!
      <% end %>
    </div>
  </div>
</div>